Feat/routing
wafflestudio/wacruit-web pull request #12
Opened 2023-07-26 09:06 UTC by designDefined

### 요약
- 마감 기한: YY-MM-DD
- 상태: 

### 태스크 URL

### 체크리스트
__PR 전__
- [ ] 칸반 생성
- [ ] pre-commit 성공
- [ ] type-label 추가

__머지 전__
- [ ] 칸반 옮기기
- [ ] 코멘트 리졸브
- [ ] squash & merge

### 작업 목록

### 테스트 방법 (Optional)

### 기타 질문 및 공유 사항 (Optional)

2023-07-26 12:19 UTC, iihyungsuk commented on src/pages/Rookie.tsx
Rookie.tsx 파일은 삭제 예정인가요?

2023-07-26 12:29 UTC, designDefined commented on src/types/apiTypes.ts
> +  }[];
아 넵 이부분은 실제 api에서 숫자로 바뀐다고 해서 지금 배포된 api docs 확인한 다음에 수정하겠습니다!

2023-07-26 13:30 UTC, joongwon commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-1.22.19.cjs
yarn dev가 안 되는데 아마 얘 때문인 거 같아요.. 뭐하는 녀석인가요?

2023-07-26 13:33 UTC, joongwon commented on src/main.tsx
> +    element: <Recruit />,
`/recruiting`이 아니라 `/recruit`이군요

2023-07-26 13:44 UTC, joongwon requested changes
수고하셨습니다! 제 `yarn dev`만 돌려주시면 approve 드리겠습니다

2023-07-26 13:44 UTC, joongwon commented on src/pages/Rookie.tsx
요게 Dashboard로 옮겨간거죠?

2023-07-26 13:44 UTC, joongwon commented on src/pages/Dashboard.tsx
> +      <Title>{recruiting ? recruiting.name : "불러오는 중..."}</Title>
404 뜨면 무한 불러오는 중..

2023-07-26 13:44 UTC, joongwon commented on src/types/constants.ts
> +  "SQL",
저희 SQL도 지원하나요? ㄷㄷ

2023-07-26 13:47 UTC, designDefined commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-1.22.19.cjs
오잉 제가 로컬에서 yarn 3.6.0 버전을 쓰고 있어서 기존에 프로젝트가 구성되어 있던 yarn 구버전과 호환되게끔 하는 코드인데, 뭔가 문제가 있나 보네요
yarn 튜토리얼 나온대로 코드 약간 고쳐볼테니 테스트 함 더 해주시와요...

2023-07-26 13:49 UTC, designDefined commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-1.22.19.cjs
@joongwon 버전 파일도 포함하게(yarn에서 하라는 대로) 다시 푸쉬했습니다! yarn install / yarn dev 돌려보시고 결과 알려주세용

2023-07-26 13:50 UTC, designDefined commented on src/types/constants.ts
> +  "SQL",
그렇더라구요ㅋㅋㅋ 뭐 백엔드에 구현은 해놨는데 정책상 변경될수는 있을듯요

2023-07-26 13:52 UTC, designDefined commented on src/pages/Rookie.tsx
넵 Rookie.tsx는 삭제할 예정입니다! 각자 브랜치에서 Rookie.tsx 작업한 부분 있으면 Dashboard.tsx에 반영해주세요!

2023-07-26 13:52 UTC, designDefined commented on src/main.tsx
> +    element: <Recruit />,
이 부분 좀 고민... recruiting으로 할까요?

2023-07-27 08:07 UTC, joongwon approved these changes

2023-07-27 09:08 UTC, designDefined commented
@joongwon @iihyungsuk @hitkoo 

일단 급한 수정은 마무리했습니다! 이 PR 머지 후 #11 #13 PR들은 메인에 rebase 하여 작업 진행하시면 될 듯 합니다

__리베이스 시 아래 사항들 주의해주시기 바랍니다!__
- announcement, resume, recruiting 관련 api 함수를 추가했습니다. `apis` 폴더에서 확인 가능합니다.
- `mocks/handler` 의 `userHnadler.ts`와 `homeHandler.ts`, 그리고 `pages/Rookie.tsx`는 #11, #13 머지 후 핫픽스에서 사라질 파일들입니다! 특히 Rookie.tsx의 변경사항의 경우 Dashboard.tsx로 옮겨주시기 바랍니다

__다음과 같은 수정사항은 #11, #13 머지 이후 반영하겠습니다__
- 리크루팅 대시보드의 무한 로딩 문제 해결
- 실제 api에 따라 타입 명세 변경

2023-07-27 09:12 UTC, merged